3.11.4
mesonbuild/protobuf pull request #13
Opened 2020-10-23 00:42 UTC by TiceCosmos

- Native build like 3.12.2
- Cross compilation add protoc native-build

2020-10-23 00:59 UTC, eli-schwartz requested changes

2020-10-23 00:59 UTC, eli-schwartz commented on meson.build
> +endif
Better to set the protoc_native variable to the regular executable, if it's a non-cross build.

Then define one generator outside of the if.

2020-10-23 01:01 UTC, eli-schwartz commented
https://github.com/mesonbuild/meson/issues/1531 is relevant.

2020-12-20 03:52 UTC, eli-schwartz commented
Sorry for the lateness of the reply.

Any particular reason to add an older version when a wrap for 3.12.2 exists already? Why not add protoc-native and protoc_gen to that instead?

2020-12-21 02:18 UTC, TiceCosmos commented
> Sorry for the lateness of the reply.
> 
> Any particular reason to add an older version when a wrap for 3.12.2 exists already? Why not add protoc-native and protoc_gen to that instead?

The only difference is version. It's ok to use 3.12.2. I will to add these features to 3.12.2.

2020-12-21 02:18 UTC, closed without merging